# This file was generated by GoReleaser. DO NOT EDIT.
cask "homebrew-cli-test" do
  desc ""
  homepage ""
  version "0.0.7"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "homebrew-cli-test"

  on_macos do
    on_intel do
      url "https://github.com/lksmsr/homebrew-cli-test/releases/download/v0.0.7/sliplane-cli_Darwin_x86_64.tar.gz"
      sha256 "7ace91146e5c5530a9d2dc2947319831c1e21bed561d30fd4eba6cda9470959a"
    end
    on_arm do
      url "https://github.com/lksmsr/homebrew-cli-test/releases/download/v0.0.7/sliplane-cli_Darwin_arm64.tar.gz"
      sha256 "0e43d083636af98fd2423624c8587f3e7e24dc73587dde8eba05151184901f4e"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/lksmsr/homebrew-cli-test/releases/download/v0.0.7/sliplane-cli_Linux_x86_64.tar.gz"
      sha256 "c4884192c07636c0d0b028d5b61277424f3ab4fca76da683d31dd94c4372da49"
    end
    on_arm do
      url "https://github.com/lksmsr/homebrew-cli-test/releases/download/v0.0.7/sliplane-cli_Linux_arm64.tar.gz"
      sha256 "7e0a11c8dcfd56f38777ace5527749116e4a3b952e4c3c8a62fa64d5e5661fcd"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/homebrew-cli-test"]
    end
  end

  # No zap stanza required
end
