# This file was generated by GoReleaser. DO NOT EDIT.
cask "homebrew-cli-test" do
  desc ""
  homepage ""
  version "0.0.5"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "homebrew-cli-test"

  on_macos do
    on_intel do
      url "https://github.com/lksmsr/homebrew-cli-test/releases/download/v0.0.5/homebrew-cli-test_Darwin_x86_64.tar.gz"
      sha256 "5ba6d14d887a6b20b7d9b439b81b390c986a98b9c7414a818ad96714f4d9b9a1"
    end
    on_arm do
      url "https://github.com/lksmsr/homebrew-cli-test/releases/download/v0.0.5/homebrew-cli-test_Darwin_arm64.tar.gz"
      sha256 "d55f7bcc157dc6611f9892190f5944153e3648a2834fe75d841bee15c4285d5e"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/lksmsr/homebrew-cli-test/releases/download/v0.0.5/homebrew-cli-test_Linux_x86_64.tar.gz"
      sha256 "18f7260639a556789f8d5951b534ae5540836ef1af1e94014ac2cdf1790f4653"
    end
    on_arm do
      url "https://github.com/lksmsr/homebrew-cli-test/releases/download/v0.0.5/homebrew-cli-test_Linux_arm64.tar.gz"
      sha256 "49b8ec90f614d58b4d349973b42670929bb6084f21992130b3ac338c6215ffbf"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/homebrew-cli-test"]
    end
  end

  # No zap stanza required
end
