# This file was generated by GoReleaser. DO NOT EDIT.
cask "sliplane-cli" do
  desc ""
  homepage ""
  version "0.0.1"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "sliplane-cli"

  on_macos do
    on_intel do
      url "https://github.com/lksmsr/homebrew-cli-test/releases/download/v0.0.1/homebrew-cli-test_Darwin_x86_64.tar.gz"
      sha256 "aba65688b961721744f49b970b36d4486985a8ef7d9afffe64d597b222306d5b"
    end
    on_arm do
      url "https://github.com/lksmsr/homebrew-cli-test/releases/download/v0.0.1/homebrew-cli-test_Darwin_arm64.tar.gz"
      sha256 "6db14e3053250d8e08a5a1c87b374cd4fc2e5abda921efd933a2e59537674033"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/lksmsr/homebrew-cli-test/releases/download/v0.0.1/homebrew-cli-test_Linux_x86_64.tar.gz"
      sha256 "2270d2b02b29436b511e9e715be592d512105f9d52ef62e18957fd7caa728202"
    end
    on_arm do
      url "https://github.com/lksmsr/homebrew-cli-test/releases/download/v0.0.1/homebrew-cli-test_Linux_arm64.tar.gz"
      sha256 "b6ec638ce4e3a1416b86c76ec999fecba865754e6ac0a972d0dbf61b0bc80d4b"
    end
  end

  # No zap stanza required
end
