# This file was generated by GoReleaser. DO NOT EDIT.
cask "sliplane-cli" do
  desc ""
  homepage ""
  version "0.0.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "sliplane-cli"

  on_macos do
    on_intel do
      url "https://github.com/lksmsr/cli-test/releases/download/v0.0.0/cli-test_Darwin_x86_64.tar.gz"
      sha256 "8bba4010d25ca394471e93f9bb1aeb24868572766bee073a791e1616ca117373"
    end
    on_arm do
      url "https://github.com/lksmsr/cli-test/releases/download/v0.0.0/cli-test_Darwin_arm64.tar.gz"
      sha256 "399cf1067efaa565f043978931e9cc543c91c3ba14e202429bfce7d8ec994728"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/lksmsr/cli-test/releases/download/v0.0.0/cli-test_Linux_x86_64.tar.gz"
      sha256 "dd0da6b4f54c1234bc95c980fc026b2c7e1cd1290ad377597ded90552b09c055"
    end
    on_arm do
      url "https://github.com/lksmsr/cli-test/releases/download/v0.0.0/cli-test_Linux_arm64.tar.gz"
      sha256 "8855126583605c39ca7fd2ac68536594e175d5a2cddd73b7881e90d8049e0541"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/sliplane-cli"]
    end
  end

  # No zap stanza required
end
