# This file was generated by GoReleaser. DO NOT EDIT.
cask "sliplane" do
  desc ""
  homepage ""
  version "0.0.8"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "sliplane"

  on_macos do
    on_intel do
      url "https://github.com/lksmsr/homebrew-cli-test/releases/download/v0.0.8/sliplane-cli_Darwin_x86_64.tar.gz"
      sha256 "ad0f743ae8236b77afb81be435823adb6946a0b8c3b5bc5074f9a28fb88ef7ed"
    end
    on_arm do
      url "https://github.com/lksmsr/homebrew-cli-test/releases/download/v0.0.8/sliplane-cli_Darwin_arm64.tar.gz"
      sha256 "e4a3fa4f1e346cf66d1e2b6b9bc85e7a2591c467f66dae8912baaf3fb14f5e28"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/lksmsr/homebrew-cli-test/releases/download/v0.0.8/sliplane-cli_Linux_x86_64.tar.gz"
      sha256 "3cb76f6b2a39e608ec13b4fbec0149ab44a36cb7f0c2e938df759846c238c287"
    end
    on_arm do
      url "https://github.com/lksmsr/homebrew-cli-test/releases/download/v0.0.8/sliplane-cli_Linux_arm64.tar.gz"
      sha256 "d3ec76b83ac07ebce8713a8c2cbe87123bad38783569053eaa3077a7f52950f5"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/homebrew-cli-test"]
    end
  end

  # No zap stanza required
end
