# This file was generated by GoReleaser. DO NOT EDIT.
cask "sliplane" do
  desc ""
  homepage ""
  version "0.0.11"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "sliplane"

  on_macos do
    on_intel do
      url "https://github.com/lksmsr/homebrew-cli-test/releases/download/v0.0.11/sliplane_Darwin_x86_64.tar.gz"
      sha256 "82c4c68c55eb923c774c863c8cb067433c1c3c91a20cedb8166d8d0d2a3e595e"
    end
    on_arm do
      url "https://github.com/lksmsr/homebrew-cli-test/releases/download/v0.0.11/sliplane_Darwin_arm64.tar.gz"
      sha256 "0955977dada706f690806cf7e3a0dc483fee1a190de67dd160894a9a54d3f1f3"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/lksmsr/homebrew-cli-test/releases/download/v0.0.11/sliplane_Linux_x86_64.tar.gz"
      sha256 "93f2373e83e8412bbfd2bd8e19c45511c37502f0ee89fc00bea7e4dddaaf3148"
    end
    on_arm do
      url "https://github.com/lksmsr/homebrew-cli-test/releases/download/v0.0.11/sliplane_Linux_arm64.tar.gz"
      sha256 "f7760bd9524d12bd4a8d59656d21ab28c8c724ca5dc6a37e64358811761d50c6"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/sliplane"]
    end
  end

  # No zap stanza required
end
